SELECT DEPTNAME, MAX(SALARY)
FROM DEPARTMENTLSM AS D, EMPLOYEELSM AS E
WHERE D.DEPTNO = E.DNO
GROUP BY DNO
HAVING AVG(SALARY)=
	(SELECT MAX(AVGSALARY)
    FROM 
		(SELECT AVG(SALARY) AS AVGSALARY
		FROM EMPLOYEELSM 
		GROUP BY DNO)AS A);