SELECT DEPTNAME, COUNT(*) AS HEADCOUNT
FROM DEPARTMENTLSM AS D, EMPLOYEELSM AS E
WHERE DNO = (SELECT DNO 
	FROM EMPLOYEELSM 
	WHERE HIREDATE = (SELECT MAX(HIREDATE) FROM EMPLOYEELSM))
AND D.DEPTNO=E.DNO
GROUP BY DNO;